# Generated by Django 3.2.8 on 2021-10-12 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=20)),
                ('etypeVehicle', models.CharField(max_length=100)),
                ('emodel', models.CharField(max_length=100)),
                ('ebrand', models.CharField(max_length=100)),
                ('eplate', models.CharField(max_length=100)),
                ('emileage', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'vehicle',
            },
        ),
    ]
